# ============================================================
#  JUNG'GAM BNG - asset build  (ASCII-only; base path via $env:SRCBASE)
#  Reads category source graphics (02-05) from the shared drive,
#  re-encodes to clean web-optimised images, renames to ASCII,
#  drops panoramic contact-sheets, classifies brand logos,
#  and writes js/gallery-manifest.js
# ============================================================
Add-Type -AssemblyName System.Drawing

$ErrorActionPreference = 'Stop'
$root = 'c:\Users\songh\junggam-bng'
$base = $env:SRCBASE
$map  = [ordered]@{ story='02. Story&Moods'; rooms='03.Room'; manpower='04.Manpower'; others='05.Others' }
$MAX  = 1600

$jpgCodec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object { $_.MimeType -eq 'image/jpeg' }
$ep = New-Object System.Drawing.Imaging.EncoderParameters(1)
$ep.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter([System.Drawing.Imaging.Encoder]::Quality, [long]82)

function To-AsciiName($cat, $name){
  $ext = [System.IO.Path]::GetExtension($name).ToLower()
  if ($name -match '99-(\d+)')      { return ($cat + '-' + $Matches[1] + $ext) }
  $bare = [System.IO.Path]::GetFileNameWithoutExtension($name)
  if ($bare -match '(\d+)\s*$')     { return ($cat + '-ab' + $Matches[1] + $ext) }
  $b = $bare -replace '[^0-9A-Za-z]+','-'
  return ($cat + '-' + $b + $ext)
}

$manifest = [ordered]@{}
$summary  = @()

foreach($cat in $map.Keys){
  $srcDir = Join-Path $base $map[$cat]
  $dstDir = Join-Path $root ('assets\graphics\' + $cat)
  New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
  $entries = New-Object System.Collections.ArrayList
  $kept = 0; $skipped = 0

  foreach($f in Get-ChildItem -LiteralPath $srcDir -File | Sort-Object Name){
    $ext = [System.IO.Path]::GetExtension($f.Name).ToLower()
    if (@('.jpg','.jpeg','.png') -notcontains $ext) { $skipped++; continue }
    $img = $null
    try { $img = [System.Drawing.Image]::FromFile($f.FullName) } catch { $skipped++; continue }
    $w = $img.Width; $h = $img.Height
    if ($w -le 0 -or $h -le 0) { $img.Dispose(); $skipped++; continue }

    if (($w / $h) -gt 2.6 -and $w -gt 1200) { $img.Dispose(); $skipped++; continue }  # contact sheets

    $maxd = [math]::Max($w,$h); $ratio = $w / $h
    $isLogo = ($cat -eq 'others' -and $ext -eq '.png' -and ($maxd -lt 200 -or (($ratio -gt 1.7 -or $ratio -lt 0.58) -and $maxd -lt 320)))
    $type = if ($isLogo) { 'logo' } else { 'photo' }

    $nw = $w; $nh = $h
    if ($maxd -gt $MAX) { $sc = $MAX / $maxd; $nw = [int][math]::Round($w * $sc); $nh = [int][math]::Round($h * $sc) }

    $outName = To-AsciiName $cat $f.Name
    $outPath = Join-Path $dstDir $outName

    try {
      if ($ext -eq '.png') {
        $bmp = New-Object System.Drawing.Bitmap($nw, $nh, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        $g = [System.Drawing.Graphics]::FromImage($bmp)
        $g.Clear([System.Drawing.Color]::Transparent)
        $g.InterpolationMode = 'HighQualityBicubic'; $g.SmoothingMode = 'HighQuality'; $g.PixelOffsetMode = 'HighQuality'
        $g.DrawImage($img, 0, 0, $nw, $nh)
        $bmp.Save($outPath, [System.Drawing.Imaging.ImageFormat]::Png)
        $g.Dispose(); $bmp.Dispose()
      } else {
        $bmp = New-Object System.Drawing.Bitmap($nw, $nh)
        $g = [System.Drawing.Graphics]::FromImage($bmp)
        $g.Clear([System.Drawing.Color]::White)
        $g.InterpolationMode = 'HighQualityBicubic'; $g.SmoothingMode = 'HighQuality'; $g.PixelOffsetMode = 'HighQuality'
        $g.DrawImage($img, 0, 0, $nw, $nh)
        $bmp.Save($outPath, $jpgCodec, $ep)
        $g.Dispose(); $bmp.Dispose()
      }
      [void]$entries.Add([pscustomobject]@{ f=$outName; w=$nw; h=$nh; t=$type })
      $kept++
    } catch { $skipped++ }
    $img.Dispose()
  }

  $sorted = $entries | Sort-Object @{ e={ if ($_.f -match '(\d+)\D*$'){[int]$Matches[1]} else {0} } }, f
  $manifest[$cat] = $sorted
  $summary += [pscustomobject]@{ cat=$cat; kept=$kept; skipped=$skipped }
}

$json = $manifest | ConvertTo-Json -Depth 6 -Compress
$js = "/* AUTO-GENERATED by build-assets.ps1 - do not edit by hand */`r`nwindow.GALLERY = $json;"
$js | Out-File -FilePath (Join-Path $root 'js\gallery-manifest.js') -Encoding utf8

$summary | ForEach-Object { Write-Output ($_.cat + ': kept=' + $_.kept + ' skipped=' + $_.skipped) }
$total = (Get-ChildItem -LiteralPath (Join-Path $root 'assets\graphics') -Recurse -File | Measure-Object Length -Sum).Sum
Write-Output ('output total MB: ' + [math]::Round($total/1MB,1))
Write-Output 'DONE'
